//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace games.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("games.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;words&gt;
        ///  &lt;word name=&quot;Дом&quot;&gt;
        ///    &lt;Definition&gt;Дом&lt;/Definition&gt;
        ///  &lt;/word&gt;
        ///  &lt;word name=&quot;Котёл&quot;&gt;
        ///    &lt;Definition&gt;Котёл&lt;/Definition&gt;
        ///  &lt;/word&gt;
        ///  &lt;word name=&quot;Вода&quot;&gt;
        ///    &lt;Definition&gt;Вода&lt;/Definition&gt;
        ///  &lt;/word&gt;
        ///  &lt;word name=&quot;Кошелёк&quot;&gt;
        ///    &lt;Definition&gt;Кошелёк&lt;/Definition&gt;
        ///  &lt;/word&gt;
        ///  &lt;word name=&quot;Компьютер&quot;&gt;
        ///    &lt;Definition&gt;Компьютер&lt;/Definition&gt;
        ///  &lt;/word&gt;
        ///  &lt;word name=&quot;Телефон&quot;&gt;
        ///    &lt;Definition&gt;Телефон&lt;/Definition&gt;
        ///  &lt;/word&gt;
        ///  &lt;word name=&quot;Мастер&quot;&gt;
        ///    &lt;De [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string XMLFile1 {
            get {
                return ResourceManager.GetString("XMLFile1", resourceCulture);
            }
        }
    }
}
